version: 2.1

orbs:
 percy: percy/agent@0.1.2

jobs:
 run_tests:
   parallelism: 3
   steps:
     - attach_workspace:
         at: .
     - run: echo "your tests run here"

workflows:
 test:
   jobs:
     - run_tests
     - percy/finalize_all:
         requires:
           - run_tests